/*
 * Beneficiary account pre-validation
 * Move your app forward with the Account Pre-Validation API
 *
 * OpenAPI spec version: 1.0.7-oas3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.swift.gpi.preval.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.swift.gpi.preval.model.AccountValidationCheckContext1Code;
import com.swift.gpi.preval.model.FinancialInstitutionIdentification20;
import com.swift.gpi.preval.model.PostalAddress26;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.Map;

/**
 * Beneficiary account verification request.
 */
@Schema(description = "Beneficiary account verification request.")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-06-19T14:52:07.265298-04:00[America/New_York]")public class AccountVerificationRequest {

  @SerializedName("correlation_identifier")
  private String correlationIdentifier = null;

  @SerializedName("context")
  private AccountValidationCheckContext1Code context = null;

  @SerializedName("uetr")
  private String uetr = null;

  @SerializedName("creditor_account")
  private String creditorAccount = null;

  @SerializedName("creditor_name")
  private String creditorName = null;

  @SerializedName("creditor_address")
  private PostalAddress26 creditorAddress = null;

  @SerializedName("creditor_organisation_identification")
  private Map creditorOrganisationIdentification = null;

  @SerializedName("creditor_agent")
  private FinancialInstitutionIdentification20 creditorAgent = null;

  @SerializedName("creditor_agent_branch_identification")
  private String creditorAgentBranchIdentification = null;
  public AccountVerificationRequest correlationIdentifier(String correlationIdentifier) {
    this.correlationIdentifier = correlationIdentifier;
    return this;
  }

  

  /**
  * Get correlationIdentifier
  * @return correlationIdentifier
  **/
  @Schema(description = "")
  public String getCorrelationIdentifier() {
    return correlationIdentifier;
  }
  public void setCorrelationIdentifier(String correlationIdentifier) {
    this.correlationIdentifier = correlationIdentifier;
  }
  public AccountVerificationRequest context(AccountValidationCheckContext1Code context) {
    this.context = context;
    return this;
  }

  

  /**
  * Get context
  * @return context
  **/
  @Schema(required = true, description = "")
  public AccountValidationCheckContext1Code getContext() {
    return context;
  }
  public void setContext(AccountValidationCheckContext1Code context) {
    this.context = context;
  }
  public AccountVerificationRequest uetr(String uetr) {
    this.uetr = uetr;
    return this;
  }

  

  /**
  * Get uetr
  * @return uetr
  **/
  @Schema(description = "")
  public String getUetr() {
    return uetr;
  }
  public void setUetr(String uetr) {
    this.uetr = uetr;
  }
  public AccountVerificationRequest creditorAccount(String creditorAccount) {
    this.creditorAccount = creditorAccount;
    return this;
  }

  

  /**
  * Get creditorAccount
  * @return creditorAccount
  **/
  @Schema(required = true, description = "")
  public String getCreditorAccount() {
    return creditorAccount;
  }
  public void setCreditorAccount(String creditorAccount) {
    this.creditorAccount = creditorAccount;
  }
  public AccountVerificationRequest creditorName(String creditorName) {
    this.creditorName = creditorName;
    return this;
  }

  

  /**
  * Get creditorName
  * @return creditorName
  **/
  @Schema(required = true, description = "")
  public String getCreditorName() {
    return creditorName;
  }
  public void setCreditorName(String creditorName) {
    this.creditorName = creditorName;
  }
  public AccountVerificationRequest creditorAddress(PostalAddress26 creditorAddress) {
    this.creditorAddress = creditorAddress;
    return this;
  }

  

  /**
  * Get creditorAddress
  * @return creditorAddress
  **/
  @Schema(description = "")
  public PostalAddress26 getCreditorAddress() {
    return creditorAddress;
  }
  public void setCreditorAddress(PostalAddress26 creditorAddress) {
    this.creditorAddress = creditorAddress;
  }
  public AccountVerificationRequest creditorOrganisationIdentification(Map creditorOrganisationIdentification) {
    this.creditorOrganisationIdentification = creditorOrganisationIdentification;
    return this;
  }

  

  /**
  * Get creditorOrganisationIdentification
  * @return creditorOrganisationIdentification
  **/
  @Schema(description = "")
  public Map getCreditorOrganisationIdentification() {
    return creditorOrganisationIdentification;
  }
  public void setCreditorOrganisationIdentification(Map creditorOrganisationIdentification) {
    this.creditorOrganisationIdentification = creditorOrganisationIdentification;
  }
  public AccountVerificationRequest creditorAgent(FinancialInstitutionIdentification20 creditorAgent) {
    this.creditorAgent = creditorAgent;
    return this;
  }

  

  /**
  * Get creditorAgent
  * @return creditorAgent
  **/
  @Schema(description = "")
  public FinancialInstitutionIdentification20 getCreditorAgent() {
    return creditorAgent;
  }
  public void setCreditorAgent(FinancialInstitutionIdentification20 creditorAgent) {
    this.creditorAgent = creditorAgent;
  }
  public AccountVerificationRequest creditorAgentBranchIdentification(String creditorAgentBranchIdentification) {
    this.creditorAgentBranchIdentification = creditorAgentBranchIdentification;
    return this;
  }

  

  /**
  * Get creditorAgentBranchIdentification
  * @return creditorAgentBranchIdentification
  **/
  @Schema(description = "")
  public String getCreditorAgentBranchIdentification() {
    return creditorAgentBranchIdentification;
  }
  public void setCreditorAgentBranchIdentification(String creditorAgentBranchIdentification) {
    this.creditorAgentBranchIdentification = creditorAgentBranchIdentification;
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AccountVerificationRequest accountVerificationRequest = (AccountVerificationRequest) o;
    return Objects.equals(this.correlationIdentifier, accountVerificationRequest.correlationIdentifier) &&
        Objects.equals(this.context, accountVerificationRequest.context) &&
        Objects.equals(this.uetr, accountVerificationRequest.uetr) &&
        Objects.equals(this.creditorAccount, accountVerificationRequest.creditorAccount) &&
        Objects.equals(this.creditorName, accountVerificationRequest.creditorName) &&
        Objects.equals(this.creditorAddress, accountVerificationRequest.creditorAddress) &&
        Objects.equals(this.creditorOrganisationIdentification, accountVerificationRequest.creditorOrganisationIdentification) &&
        Objects.equals(this.creditorAgent, accountVerificationRequest.creditorAgent) &&
        Objects.equals(this.creditorAgentBranchIdentification, accountVerificationRequest.creditorAgentBranchIdentification);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(correlationIdentifier, context, uetr, creditorAccount, creditorName, creditorAddress, creditorOrganisationIdentification, creditorAgent, creditorAgentBranchIdentification);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AccountVerificationRequest {\n");
    
    sb.append("    correlationIdentifier: ").append(toIndentedString(correlationIdentifier)).append("\n");
    sb.append("    context: ").append(toIndentedString(context)).append("\n");
    sb.append("    uetr: ").append(toIndentedString(uetr)).append("\n");
    sb.append("    creditorAccount: ").append(toIndentedString(creditorAccount)).append("\n");
    sb.append("    creditorName: ").append(toIndentedString(creditorName)).append("\n");
    sb.append("    creditorAddress: ").append(toIndentedString(creditorAddress)).append("\n");
    sb.append("    creditorOrganisationIdentification: ").append(toIndentedString(creditorOrganisationIdentification)).append("\n");
    sb.append("    creditorAgent: ").append(toIndentedString(creditorAgent)).append("\n");
    sb.append("    creditorAgentBranchIdentification: ").append(toIndentedString(creditorAgentBranchIdentification)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
