/*
 * Beneficiary account pre-validation
 * Move your app forward with the Account Pre-Validation API
 *
 * OpenAPI spec version: 1.0.7-oas3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.swift.gpi.preval.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.swift.gpi.preval.model.OrganisationIdentificationSchemeName1Choice;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;

/**
 * Information related to an identification of an organisation.
 */
@Schema(description = "Information related to an identification of an organisation.")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-06-19T14:52:07.265298-04:00[America/New_York]")public class GenericOrganisationIdentification1 {

  @SerializedName("identification")
  private String identification = null;

  @SerializedName("scheme_name")
  private OrganisationIdentificationSchemeName1Choice schemeName = null;

  @SerializedName("issuer")
  private String issuer = null;
  public GenericOrganisationIdentification1 identification(String identification) {
    this.identification = identification;
    return this;
  }

  

  /**
  * Get identification
  * @return identification
  **/
  @Schema(required = true, description = "")
  public String getIdentification() {
    return identification;
  }
  public void setIdentification(String identification) {
    this.identification = identification;
  }
  public GenericOrganisationIdentification1 schemeName(OrganisationIdentificationSchemeName1Choice schemeName) {
    this.schemeName = schemeName;
    return this;
  }

  

  /**
  * Get schemeName
  * @return schemeName
  **/
  @Schema(description = "")
  public OrganisationIdentificationSchemeName1Choice getSchemeName() {
    return schemeName;
  }
  public void setSchemeName(OrganisationIdentificationSchemeName1Choice schemeName) {
    this.schemeName = schemeName;
  }
  public GenericOrganisationIdentification1 issuer(String issuer) {
    this.issuer = issuer;
    return this;
  }

  

  /**
  * Get issuer
  * @return issuer
  **/
  @Schema(description = "")
  public String getIssuer() {
    return issuer;
  }
  public void setIssuer(String issuer) {
    this.issuer = issuer;
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GenericOrganisationIdentification1 genericOrganisationIdentification1 = (GenericOrganisationIdentification1) o;
    return Objects.equals(this.identification, genericOrganisationIdentification1.identification) &&
        Objects.equals(this.schemeName, genericOrganisationIdentification1.schemeName) &&
        Objects.equals(this.issuer, genericOrganisationIdentification1.issuer);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(identification, schemeName, issuer);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GenericOrganisationIdentification1 {\n");
    
    sb.append("    identification: ").append(toIndentedString(identification)).append("\n");
    sb.append("    schemeName: ").append(toIndentedString(schemeName)).append("\n");
    sb.append("    issuer: ").append(toIndentedString(issuer)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
