/*
 * Beneficiary account pre-validation
 * Move your app forward with the Account Pre-Validation API
 *
 * OpenAPI spec version: 1.0.7-oas3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.swift.gpi.preval.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.swift.gpi.preval.model.AccountValidationResponse1Code;
import com.swift.gpi.preval.model.AccountValidationResponse2Code;
import com.swift.gpi.preval.model.AccountValidationResponse3Code;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;

/**
 * ValidationCheckReponse1
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2019-06-19T14:52:07.265298-04:00[America/New_York]")public class ValidationCheckReponse1 {

  @SerializedName("account_validation_status")
  private AccountValidationResponse3Code accountValidationStatus = null;

  @SerializedName("creditor_account_match")
  private AccountValidationResponse2Code creditorAccountMatch = null;

  @SerializedName("creditor_name_match")
  private AccountValidationResponse1Code creditorNameMatch = null;

  @SerializedName("creditor_address_match")
  private AccountValidationResponse1Code creditorAddressMatch = null;

  @SerializedName("creditor_organisation_identification_match")
  private AccountValidationResponse1Code creditorOrganisationIdentificationMatch = null;
  public ValidationCheckReponse1 accountValidationStatus(AccountValidationResponse3Code accountValidationStatus) {
    this.accountValidationStatus = accountValidationStatus;
    return this;
  }

  

  /**
  * Get accountValidationStatus
  * @return accountValidationStatus
  **/
  @Schema(required = true, description = "")
  public AccountValidationResponse3Code getAccountValidationStatus() {
    return accountValidationStatus;
  }
  public void setAccountValidationStatus(AccountValidationResponse3Code accountValidationStatus) {
    this.accountValidationStatus = accountValidationStatus;
  }
  public ValidationCheckReponse1 creditorAccountMatch(AccountValidationResponse2Code creditorAccountMatch) {
    this.creditorAccountMatch = creditorAccountMatch;
    return this;
  }

  

  /**
  * Get creditorAccountMatch
  * @return creditorAccountMatch
  **/
  @Schema(description = "")
  public AccountValidationResponse2Code getCreditorAccountMatch() {
    return creditorAccountMatch;
  }
  public void setCreditorAccountMatch(AccountValidationResponse2Code creditorAccountMatch) {
    this.creditorAccountMatch = creditorAccountMatch;
  }
  public ValidationCheckReponse1 creditorNameMatch(AccountValidationResponse1Code creditorNameMatch) {
    this.creditorNameMatch = creditorNameMatch;
    return this;
  }

  

  /**
  * Get creditorNameMatch
  * @return creditorNameMatch
  **/
  @Schema(required = true, description = "")
  public AccountValidationResponse1Code getCreditorNameMatch() {
    return creditorNameMatch;
  }
  public void setCreditorNameMatch(AccountValidationResponse1Code creditorNameMatch) {
    this.creditorNameMatch = creditorNameMatch;
  }
  public ValidationCheckReponse1 creditorAddressMatch(AccountValidationResponse1Code creditorAddressMatch) {
    this.creditorAddressMatch = creditorAddressMatch;
    return this;
  }

  

  /**
  * Get creditorAddressMatch
  * @return creditorAddressMatch
  **/
  @Schema(required = true, description = "")
  public AccountValidationResponse1Code getCreditorAddressMatch() {
    return creditorAddressMatch;
  }
  public void setCreditorAddressMatch(AccountValidationResponse1Code creditorAddressMatch) {
    this.creditorAddressMatch = creditorAddressMatch;
  }
  public ValidationCheckReponse1 creditorOrganisationIdentificationMatch(AccountValidationResponse1Code creditorOrganisationIdentificationMatch) {
    this.creditorOrganisationIdentificationMatch = creditorOrganisationIdentificationMatch;
    return this;
  }

  

  /**
  * Get creditorOrganisationIdentificationMatch
  * @return creditorOrganisationIdentificationMatch
  **/
  @Schema(required = true, description = "")
  public AccountValidationResponse1Code getCreditorOrganisationIdentificationMatch() {
    return creditorOrganisationIdentificationMatch;
  }
  public void setCreditorOrganisationIdentificationMatch(AccountValidationResponse1Code creditorOrganisationIdentificationMatch) {
    this.creditorOrganisationIdentificationMatch = creditorOrganisationIdentificationMatch;
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ValidationCheckReponse1 validationCheckReponse1 = (ValidationCheckReponse1) o;
    return Objects.equals(this.accountValidationStatus, validationCheckReponse1.accountValidationStatus) &&
        Objects.equals(this.creditorAccountMatch, validationCheckReponse1.creditorAccountMatch) &&
        Objects.equals(this.creditorNameMatch, validationCheckReponse1.creditorNameMatch) &&
        Objects.equals(this.creditorAddressMatch, validationCheckReponse1.creditorAddressMatch) &&
        Objects.equals(this.creditorOrganisationIdentificationMatch, validationCheckReponse1.creditorOrganisationIdentificationMatch);
  }

  @Override
  public int hashCode() {
    return java.util.Objects.hash(accountValidationStatus, creditorAccountMatch, creditorNameMatch, creditorAddressMatch, creditorOrganisationIdentificationMatch);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ValidationCheckReponse1 {\n");
    
    sb.append("    accountValidationStatus: ").append(toIndentedString(accountValidationStatus)).append("\n");
    sb.append("    creditorAccountMatch: ").append(toIndentedString(creditorAccountMatch)).append("\n");
    sb.append("    creditorNameMatch: ").append(toIndentedString(creditorNameMatch)).append("\n");
    sb.append("    creditorAddressMatch: ").append(toIndentedString(creditorAddressMatch)).append("\n");
    sb.append("    creditorOrganisationIdentificationMatch: ").append(toIndentedString(creditorOrganisationIdentificationMatch)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
